{% set name = "minorminer" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/minorminer/archive/refs/tags/{{ version }}.tar.gz
  sha256: 83c4a739d4dd3b87b223581801545546a41aec15315e223b55e994371361ec34

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [python_impl == 'pypy' and py==38 and aarch64 and linux]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-networkx >=0.8.10
    - fasteners
    - homebase
    - networkx
    - numpy
    - python
    - rectangle-packer >=2.0.1
    - scipy

test:
  imports:
    - minorminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/minorminer
  summary: heuristic algorithm to find graph minor embeddings
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
