{% set name = "minorminer" %}
{% set version = "0.2.8.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minorminer-{{ version }}.tar.gz
  sha256: 66fb007f688c53a659ccae9b4b0a2b3c6b87853fe66de6b037562f87aa17a01b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-networkx >=0.8.10
    - fasteners
    - homebase
    - networkx
    - numpy
    - python
    - rectangle-packer >=2.0.1
    - scipy

test:
  imports:
    - minorminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/minorminer
  summary: heuristic algorithm to find graph minor embeddings
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
