{% set name = "minorminer" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/minorminer/archive/refs/tags/{{ version }}.tar.gz
  sha256: 61420a7f467c268dbf9dde109c5ec89219af0ddd35bd26aa457c42403ec119f7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [python_impl == 'pypy' and py==38 and aarch64 and linux]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-networkx >=0.8.10
    - fasteners >=0.15
    - homebase >=1.0.1
    - networkx >=2.4
    - numpy >=1.21.6
    - python
    - rectangle-packer >=2.0.1
    - scipy >=1.7.3

test:
  imports:
    - minorminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/minorminer
  summary: heuristic algorithm to find graph minor embeddings
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
