{% set name = "minorminer" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/minorminer/archive/refs/tags/{{ version }}.tar.gz
  sha256: d74e9c8345094c9dae4c1c6421557e4fdb81b3efce00c0b8b0459e3db09f5083

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2
  skip: true  # [python_impl == 'pypy' and py==38 and aarch64 and linux]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - dwave-networkx >=0.8.10
    - fasteners
    - homebase
    - networkx
    - numpy
    - python
    - rectangle-packer >=2.0.1
    - scipy

test:
  imports:
    - minorminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/minorminer
  summary: heuristic algorithm to find graph minor embeddings
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
